### PR TITLE
Added my project: Simon Says Game Web Version.

### PR DESCRIPTION
**Pull request by mishraRj**
Simon Says is a web-based interactive game developed using HTML, CSS, and JavaScript, where players must replicate a sequence of colors by the game. The project features a user-friendly interface, engaging animations to enhance the gameplay experience, testing players' memory and reflexes as they try to keep up with increasingly complex sequences."

### CODE REVIEW

**Comment by mishraRj** [comment]
> ### ✅ Deploy Preview for _the-wall-of-projects_ ready!
> Name	Link
> 🔨 Latest commit	[5ca1ad0](https://github.com/MrAshwin2142/The-Wall-of-Projects/commit/5ca1ad07aa4503c990a7da62f7fa1f34439e0555)
> 🔍 Latest deploy log	https://app.netlify.com/sites/the-wall-of-projects/deploys/670bc6f3f453b1000871e619
> 😎 Deploy Preview	https://deploy-preview-124--the-wall-of-projects.netlify.app
> 📱 Preview on mobile	
> Toggle QR Code...
> _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/the-wall-of-projects/configuration/notifications#deploy-webhooks)._

what does it mean !! @Ashwin1902

**Comment by mishraRj** [comment]
@Ashwin1902 Sir plz add hacktoberfest label and hacktoberfest accepted label before merging my PR.. 
Thankyou!
It means a lot for my hacktoberfest journey sir.

**Comment by MrAshwin2142** [comment]
Thank you for contributing in The Wall of Projects, and best of luck for your open source journey.

**Comment by MrAshwin2142** [comment]
> > ### ✅ Deploy Preview for _the-wall-of-projects_ ready!
> > Name	Link
> > 🔨 Latest commit	[5ca1ad0](https://github.com/MrAshwin2142/The-Wall-of-Projects/commit/5ca1ad07aa4503c990a7da62f7fa1f34439e0555)
> > 🔍 Latest deploy log	https://app.netlify.com/sites/the-wall-of-projects/deploys/670bc6f3f453b1000871e619
> > 😎 Deploy Preview	https://deploy-preview-124--the-wall-of-projects.netlify.app
> > 📱 Preview on mobile
> > Toggle QR Code...
> > _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/the-wall-of-projects/configuration/notifications#deploy-webhooks)._
> 
> what does it mean !! @MrAshwin2142


This project is hosted on netlify so for evey PR netlify does all necessary checks. And give us preview of project for particular PR.

**Comment by mishraRj** [comment]
@MrAshwin2142 Sir plz add hacktober fest accepted label on this

**Pull request merged**
