### PR TITLE
Added Style and Social icons

### PR DESCRIPTION
**Pull request by Shoyebaktar-shirol**
-Changes the color of background .
-changes the color of  Text called "Add New Project " and "STAR CONTRIBUTORS" .
-Added the social icons .
-Added the footer.

Video Link :-

https://github.com/MrAshwin2142/The-Wall-of-Projects/assets/113618917/df24556e-5682-48fd-8da7-d346cde30a64

Please Review this, then tell me if you want to add any other things.

### CODE REVIEW

**Review by MrAshwin2142 — CHANGES_REQUESTED** [review]
Your work on the background and text changes is great! Could you, for now, remove the social icons section?

**Comment by Shoyebaktar-shirol** [comment]
Okey i will remove, is there any mistake in that .

**Comment by MrAshwin2142** [comment]
Thank you for your contributions and quick adjustments!

**Comment by Shoyebaktar-shirol** [comment]
Okey thank you @MrAshwin2142  for giving the chance of contribution, in future if you added any more projects I feel happy to contribute on that ☺️.

**Comment by MrAshwin2142** [comment]
you can contribute in https://github.com/MrAshwin2142/OpenQuotes

**Pull request merged**
