### PR TITLE
Updated script.js to add a active class to project buttons 

### PR DESCRIPTION
**Pull request by laibatariq07**
**Issue**
Addresses the issue #32 : "Add Active Class to Project Buttons"

**Changes Made**
-  Added 'active' class on button click to change the background color to black.
- Keeping track of the currently clicked button.
- Removed the 'active' class from previously clicked button ensuring only one button has the active class at a time.

### CODE REVIEW

**Review by MrAshwin2142 — CHANGES_REQUESTED** [review]
Thank you, ZXY, for your PR to implement the active button issue. I noticed that in some cases, after deactivating a project button, the active class is not removed from the button.
I've attached a screenshot for reference .

Screenshot 2023-11-11 170211

**Comment by laibatariq07** [comment]
Please review the changes again.

**Comment by MrAshwin2142** [comment]
Thank you for your amazing contribution...

**Comment by laibatariq07** [comment]
2nd Last commit with the name "Update script.js". if statement should not be replaced with else-if.

**Pull request merged**
