### PR TITLE
Improved and Mobile Friendly UI

### PR DESCRIPTION
**Pull request by JohnPatrickAncajas**
Added screen responsive layout.
Added responsive text typography.
Added interaction and hover effects.
Added hr to act as section dividers.
Added line-height to lessen text traffic.
Added a new project.
Adjusted HTML for better readability and design.
Adjusted JS project content spelling for better readability and design. Adjusted CSS values to rem to make it more responsive. Adjusted colors for better readability and design. Adjusted title font-family for better design.

### CODE REVIEW

**Review by MrAshwin2142 — APPROVED** [review]
Everything looks perfect but <br> is not a recommended way, we can you css to make a gap btwn element using padding or margin

**Comment by JohnPatrickAncajas** [comment]
Hello sir! I did make it like that before but I thought a visual difference will be a better indicator than empty space of different content. I will change it back to empty space then instead of the line in a few hours.

**Comment by MrAshwin2142** [comment]
hey @JohnPatrickAncajas  I'm not talking about spacing, but using ```<br>``` is not recommended.

**Comment by JohnPatrickAncajas** [comment]
Oh that one, that's my bad then. I'll change that instead of the <hr> later. Sorry for the trouble, I'm still learning. Thank you for the heads up, sir!

**Comment by MrAshwin2142** [comment]
no problem ..!

**Comment by MrAshwin2142** [comment]
do it on your pace..

**Pull request merged**
