### PR TITLE
Updated search feature

### PR DESCRIPTION
**Pull request by Victorthedev**
Added autocomplete feature for search

### CODE REVIEW

**Comment by Victorthedev** [comment]
@MrAshwin2142 Sure no problem, working on it now

**Comment by MrAshwin2142** [comment]
Any update @Victorthedev ??

**Comment by Victorthedev** [comment]
> Any update @Victorthedev ??

Yes, not done cause i've been sick for a while now. Sorry for the delays

**Comment by MrAshwin2142** [comment]
@Victorthedev no problem get well soon, Take care .

**Pull request closed without merging**
